### ISSUE TITLE
Skipping tests from runner

### ISSUE THREAD

**Issue by ivo5307** [CafeHub/opencafe#36]
Another useful feature which i will be useful for everybody is:

It is possible some tests to work upstream and not downstream.

For example:
https://github.com/stackforge/cloudroast/tree/master/cloudroast/compute/integration/volumes/boot_from_volume/v1

I want to run all tests without rebuild downstream. Which is not possible currently.

**Comment by jidar** [comment]
This would require a revamping of the tag system.  A runner plugin is being developed that will support scripted runs, allowing you to define exact lists of tests.

**Comment by jidar** [comment]
This issue was solved with the inclusion of the --file option on the parallel runner, and obviated by the inclusion of the brewfile paradigm.
