### ISSUE TITLE
cafe-config init should be automatic

### ISSUE THREAD

**Issue by seemethere** [CafeHub/opencafe#37]
# Overview
Running `cafe-config init` after pip install opencafe creates an un-needed layer of complexity on the part of using opencafe.

# Proposal:
When importing opencafe, or using opencafe, opencafe will search if `$VIRTUAL_ENV/.opencafe` exists and then will do everything that `cafe-config init` does perhaps with a warning that it's being created?

**Comment by jidar** [comment]
The python community looks down upon making things 'auto-run' at install, and I agree.  'init' used to be automatic, but was changed to it's current state to be more in line with how other python packages work.
It's generally agreed that 'install' and 'deploy' should be separate processes.
