### ISSUE TITLE
Plugins should be pushed out of this repo and into their own repos

### ISSUE THREAD

**Issue by seemethere** [CafeHub/opencafe#38]
# Overview
The idea of plugins is that they can plug in and out functionality leaving the base as lightweight as possible. This purpose is kind of defeated with the way plugins are handled in opencafe with them being included in the module but not activated until the PluginManager actually installs them.

This makes it confusing for anyone and upgrading/uninstalling plugins becomes a nightmare.

Also, should plugins share the same direct namespace as opencafe?

# Proposal
We put the plugins into CafeHub and they should be pip installable like anything other python module. They are meant to extend opencafe and not be within its base package.

**Comment by jidar** [comment]
@bucknerns I think you've already done this, no?

**Comment by bucknerns** [comment]
Yep it's in my version of opencafe.
