### ISSUE TITLE
Re-work OpenCafe docs to reflect the GitHub review workflow

### ISSUE THREAD

**Issue by dwalleck** [CafeHub/opencafe#40]
Our commit docs currently reference how to work with Gerrit. They will need to be updated to reflect working in GitHub before we can say we are done with the transition from OpenStack.

**Comment by seemethere** [comment]
I'd suggest a CONTRIBUTING.md at the base level so that it pops up every-time someone is submitting a pull request.

**Comment by seemethere** [comment]
An example: https://github.com/google/grumpy/blob/master/CONTRIBUTING.md

**Comment by jidar** [comment]
Was this addressed once 43 and 44 where merged?

**Comment by jidar** [comment]
Was this addressed once 43 and 44 where merged?
